version: '3.8'

services:
  flask:
    build:
      context: .
    ports:
      - 8000:5000
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    links:
      - db

  db:
    image: mongo:latest
    hostname: ${MONGO_HOST}
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - 27017:27017
